added Schema and ERD
kalviumcommunity/Customer-Relationship-Management pull request #1
Opened 2023-09-25 18:00 UTC by popeinabar

this pull request consists of schema and ERD diagram for Customer-Relationship-Management and here is the [video 1](https://www.loom.com/share/f2b9305ca55e4d05809550a90da67e2d?sid=63dec994-8f42-43ff-86d2-ef07a711a46a) and [video 2](https://www.loom.com/share/049c8e9f03f441e6bb37aa1488241607?sid=d188e797-5326-4223-9691-a4561b47ff1e) where I am explaining schema and ERD

[video](https://www.loom.com/share/db5710380ed44baba5ca184886ad0ec6?sid=58e2cf7b-a683-493b-ad9e-599eaab6e72b) for milestone 2

2023-09-27 11:48 UTC, th3c0d3br34ker commented
Please schedule a viva with me.

2023-09-29 06:32 UTC, th3c0d3br34ker requested changes
thanks @popeinabar, as per our discussion during the viva, please do the required changes and let me know.

2023-09-29 08:30 UTC, popeinabar commented
I updated the schema and erd based on the feedback provided. The commit can be found above.

2023-09-29 08:48 UTC, th3c0d3br34ker requested changes
thanks @popeinabar, as per the viva taken, there are still some changes which need to be done. please go through the comments and resolve them.

2023-09-29 08:48 UTC, th3c0d3br34ker commented on Screenshot 2023-09-29 at 12.52.15 PM.png
![image](https://github.com/kalviumcommunity/Customer-Relationship-Management/assets/60807938/beb8ffc7-b67e-4b8a-bc9d-2cb0f674a440)


The the relationship between `Roles` and `Product` should be between `User` and `Product`.

2023-10-10 18:11 UTC, th3c0d3br34ker commented
hey @popeinabar please consider merging this and raise a separate PR for `DDL commands`.

please consider re-submitting with the correct links.

2023-10-10 18:14 UTC, th3c0d3br34ker commented
please schedule a viva as well, as per my observation, this submission ignores our previous discussion done during the viva.

2023-10-11 03:38 UTC, popeinabar commented
The ERD is updated according to our previous conversation.

2023-10-12 06:09 UTC, th3c0d3br34ker commented
hey @popeinabar, please merge this PR for `ERD` and `Schema`. as per discussion during viva.

2023-10-12 06:09 UTC, th3c0d3br34ker approved these changes

2023-10-13 04:05 UTC, merged